version: '3.8'
services:
  broker:
    image: registry.logstore:5000/logsn/broker
    ports:
      - 3001:3000

  validator:
    image: registry.logstore:5000/logsn/broker
    ports:
      - 3002:3000
