version: '3.8'
services:
  broker-au-1:
    image: registry.logstore:5000/logsn/broker
    ports:
      - 3001:3000
    deploy:
      placement:
        constraints:
          - nodename==logsn-au-1

  validator-au-1:
    image: registry.logstore:5000/logsn/validator
    ports:
      - 3002:3000
    deploy:
      placement:
        constraints:
          - nodename==logsn-au-1

  broker-eu-1:
    image: registry.logstore:5000/logsn/broker
    ports:
      - 3003:3000
    deploy:
      placement:
        constraints:
          - nodename==logsn-eu-1

  validator-eu-1:
    image: registry.logstore:5000/logsn/validator
    ports:
      - 3004:3000
    deploy:
      placement:
        constraints:
          - nodename==logsn-eu-1

  broker-us-1:
    image: registry.logstore:5000/logsn/broker
    ports:
      - 3005:3000
    deploy:
      placement:
        constraints:
          - nodename==logsn-us-1

  validator-us-1:
    image: registry.logstore:5000/logsn/validator
    ports:
      - 3006:3000
    deploy:
      placement:
        constraints:
          - nodename==logsn-us-1
