version: '3.8'
services:
  broker-au-1:
    image: registry.logstore:5000/logsn/broker
    ports:
      - 3011:3000
    deploy:
      placement:
        constraints:
          - node==logsn-au-1

  validator-au-1:
    image: registry.logstore:5000/logsn/validator
    ports:
      - 3012:3000
    deploy:
      placement:
        constraints:
          - node==logsn-au-1

  broker-eu-1:
    image: registry.logstore:5000/logsn/broker
    ports:
      - 3011:3000
    deploy:
      placement:
        constraints:
          - node==logsn-eu-1

  validator-eu-1:
    image: registry.logstore:5000/logsn/validator
    ports:
      - 3012:3000
    deploy:
      placement:
        constraints:
          - node==logsn-eu-1

  broker-us-1:
    image: registry.logstore:5000/logsn/broker
    ports:
      - 3011:3000
    deploy:
      placement:
        constraints:
          - node==logsn-us-1

  validator-us-1:
    image: registry.logstore:5000/logsn/validator
    ports:
      - 3012:3000
    deploy:
      placement:
        constraints:
          - node==logsn-us-1
